[package]
name = "pairing"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
proto.workspace = true
model.workspace = true
spake2.workspace = true
ed25519-dalek.workspace = true
hkdf.workspace = true
sha2.workspace = true
rand_core.workspace = true
subtle.workspace = true
zeroize.workspace = true

[lints]
workspace = true
